Include newbie clarification comments. Include comments for VS 2010 include 'to-ignore' from upstream msysgit
Signed-off-by: Philip Oakley <philipoakley@iee.org>

diff --git a/compat/vcbuild/msvc-build b/compat/vcbuild/msvc-build
--- a/compat/vcbuild/msvc-build
+++ b/compat/vcbuild/msvc-build
@@ -1,6 +1,8 @@
 #!/bin/sh
 
-set -e
+# This msvc-build command should be executed from the msysgit directory level
+# This is so that the 'cd/git' step works and the subequent operations have the right msysgit super directory.
+set -e # Exit immediately if a command exits with a nonzero exit status.
 
 gui=
 clean=
@@ -28,9 +30,13 @@ t)
 	case "$gui" in
 	t)
 		rm -rf git.sln libgit
+		# remove all the new VS2010 stuff as well
+		# rm -rf git.sdf
 		;;
 	'')
 		make clean
+		# surely needs "make clean MSVC=1"
+		# otherwise it could assume the wrong make products [MinGW vs Windows].
 		;;
 	esac
 	exit
@@ -47,12 +53,17 @@ test -z "$to_ignore" || {
 test -d msvcgit || git clone git://repo.or.cz/msvcgit.git
 
 vsvars=
+# assume cl.exe will populate its relevant environment variables
+# if cl.exe does not exist, populate vsvars with the most recent Visual Studio path
 type cl.exe 2> /dev/null ||
 vsvars="$(ls -t \
 	"$PROGRAMFILES/Microsoft Visual Studio"*/Common7/Tools/vsvars32.bat |
 	head -n 1)"
 
+
 config_mak=
+# if a config.mak file (dot, not underscore) exists, back it up,
+# remember the backup file name in config_mak.
 test -f config.mak &&
 config_mak=config.mak.bup.$$ &&
 mv config.mak $config_mak
@@ -73,5 +84,6 @@ fi
 
 cmd /c msvc-build.cmd
 
+# if we made a backup file (name in config_mak), then restore it.
 test -z "$config_mak" ||
 mv $config_mak config.mak
